environments:
  {{ .Environment.Name }}:
    values:
      - ./envs/{{ .Environment.Name }}/env.yaml

---
releases:
  - name: nginx-{{ .Environment.Name }}
    namespace: default
    chart: ./nginx-chart
    labels:
      app: nginx-{{ .Environment.Name }}
    values:
      - ./values/values.yaml.gotmpl