version: "3.9"

services:
  back1:
    image: nginx:alpine
    container_name: back1
    volumes:
      - ./back1/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backs-net

  back2:
    image: nginx:alpine
    container_name: back2
    volumes:
      - ./back2/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backs-net

  balanc:
    image: nginx:alpine
    container_name: balanc
    volumes:
      - ./balanc/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - back1
      - back2
    networks:
      - backs-net

networks:
  backs-net:
    driver: bridge
